using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static QuickInfo.NodeFactory;

namespace QuickInfo.Processors
{
    public sealed class Emoticons : IProcessor
    {
        private readonly HashSet<string> triggers = new HashSet<string>
        {
            "emoticons",
            "smile",
            "smiles",
            "asciimoji"
        };

        /// <summary>
        /// Source - http://asciimoji.com/
        /// </summary>
        private readonly Dictionary<string, string> emoticons = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["acid"] = @"⊂(◉‿◉)つ",
            ["afraid"] = @"(ㆆ _ ㆆ)",
            ["angel"] = @"☜(⌒▽⌒)☞",
            ["angry"] = @"•`_´•",
            ["arrowhead"] = @"⤜(ⱺ ʖ̯ⱺ)⤏",
            ["apple"] = @"",
            ["ass"] = @"(‿|‿)",
            ["awkward"] = @"•͡˘㇁•͡˘",
            ["bat"] = @"/|\ ^._.^ /|\",
            ["bear"] = @"ʕ·͡ᴥ·ʔ",
            ["bearflip"] = @"ʕノ•ᴥ•ʔノ ︵ ┻━┻",
            ["bearhug"] = @"ʕっ•ᴥ•ʔっ",
            ["because"] = @"∵",
            ["bigheart"] = @"❤",
            ["blackeye"] = @"0__#",
            ["blubby"] = @"(      0    _   0    )",
            ["blush"] = @"(˵ ͡° ͜ʖ ͡°˵)",
            ["bond"] = @"┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿",
            ["boobs"] = @"( . Y . )",
            ["bored"] = @"(-_-)",
            ["bribe"] = @"( •͡˘ _•͡˘)ノð",
            ["bubbles"] = @"( ˘ ³˘)ノ°ﾟº❍｡",
            ["butterfly"] = @"ƸӜƷ",
            ["cat"] = @"(= ФェФ=)",
            ["catlenny"] = @"( ͡° ᴥ ͡°)",
            ["check"] = @"✓",
            ["chubby"] = @"╭(ʘ̆~◞౪◟~ʘ̆)╮",
            ["claro"] = @"(͡ ° ͜ʖ ͡ °)",
            ["clique"] = @"ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ",
            ["cloud"] = @"☁",
            ["club"] = @"♣",
            ["coffee"] = @"c[_]",
            ["cmd"] = @"⌘",
            ["cool"] = @"(•_•) ( •_•)>⌐■-■ (⌐■_■)",
            ["copy"] = @"©",
            ["creep"] = @"ԅ(≖‿≖ԅ)",
            ["creepcute"] = @"ƪ(ړײ)‎ƪ​​",
            ["crim3s"] = @"( ✜︵✜ )",
            ["cross"] = @"†",
            ["cry"] = @"(╥﹏╥)",
            ["crywave"] = @"( ╥﹏╥) ノシ",
            ["cute"] = @"(｡◕‿‿◕｡)",
            ["d1"] = @"⚀",
            ["d2"] = @"⚁",
            ["d3"] = @"⚂",
            ["d4"] = @"⚃",
            ["d5"] = @"⚄",
            ["d6"] = @"⚅",
            ["damnyou"] = @"(ᕗ ͠° ਊ ͠° )ᕗ",
            ["dance"] = @"ᕕ(⌐■_■)ᕗ ♪♬",
            ["dead"] = @"x⸑x",
            ["dealwithit"] = @"(⌐■_■)",
            ["delta"] = @"Δ",
            ["depressed"] = @"(︶︹︶)",
            ["derp"] = @"☉ ‿ ⚆",
            ["diamond"] = @"♦",
            ["dog"] = @"(◕ᴥ◕ʋ)",
            ["dollar"] = @"$",
            ["dollarbill"] = @"[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅]",
            ["dong"] = @"(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄",
            ["donger"] = @"ヽ༼ຈل͜ຈ༽ﾉ",
            ["dontcare"] = @"╭∩╮（︶︿︶）╭∩╮",
            ["do not want"] = @"ヽ(｀Д´)ﾉ",
            ["dope"] = @"<(^_^)>",
            ["<<"] = @"«",
            [">>"] = @"»",
            ["doubleflat"] = @"𝄫",
            ["doublesharp"] = @"𝄪",
            ["doubletableflip"] = @"┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻",
            ["down"] = @"↓",
            ["duckface"] = @"(・3・)",
            ["duel"] = @"ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-",
            ["duh"] = @"(≧︿≦)",
            ["dunno"] = @"¯\(°_o)/¯",
            ["ebola"] = @"ᴇʙᴏʟᴀ",
            ["ellipsis"] = @"…",
            ["emdash"] = @"–",
            ["emptystar"] = @"☆",
            ["emptytriangle"] = @"△",
            ["endure"] = @"(҂◡_◡) ᕤ",
            ["envelope"] = @"✉︎",
            ["epsilon"] = @"ɛ",
            ["euro"] = @"€",
            ["evil"] = @"ψ(｀∇´)ψ",
            ["evillenny"] = @"(͠≖ ͜ʖ͠≖)",
            ["execution"] = @"(⌐■_■)︻╦╤─   (╥﹏╥)",
            ["facebook"] = @"(╯°□°)╯︵ ʞooqǝɔɐɟ",
            ["facepalm"] = @"(－‸ლ)",
            ["fart"] = @"(ˆ⺫ˆ๑)<3",
            ["fight"] = @"(ง •̀_•́)ง",
            ["finn"] = @"| (• ◡•)|",
            ["fish"] = "<\"((( < 3",
            ["5"] = @"卌",
            ["5/8"] = @"⅝",
            ["flat"] = @"♭",
            ["flexing"] = @"ᕙ(`▽´)ᕗ",
            ["flipped"] = @"┬─┬ ︵ /(.□. \）",
            ["flower"] = @"(✿◠‿◠)",
            ["f"] = @"✿",
            ["fly"] = @"─=≡Σ((( つ◕ل͜◕)つ",
            ["friendflip"] = @"(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)",
            ["frown"] = @"(ღ˘⌣˘ღ)",
            ["fuckoff"] = @"୧༼ಠ益ಠ╭∩╮༽",
            ["fuckyou"] = @"┌П┐(ಠ_ಠ)",
            ["gentleman"] = @"ಠ_ರೃ",
            ["ghast"] = @"= _ =",
            ["ghost"] = @"༼ つ ❍_❍ ༽つ",
            ["gift"] = @"(´・ω・)っ由",
            ["gimme"] = @"༼ つ ◕_◕ ༽つ",
            ["glitter"] = @"(*・‿・)ノ⌒*:･ﾟ✧",
            ["glasses"] = @"(⌐ ͡■ ͜ʖ ͡■)",
            ["glassesoff"] = @"( ͡° ͜ʖ ͡°)ﾉ⌐■-■",
            ["glitterderp"] = @"(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ✧",
            ["gloomy"] = @"(_゜_゜_)",
            ["goatse"] = @"(з๏ε)",
            ["gotit"] = @"(☞ﾟ∀ﾟ)☞",
            ["greet"] = @"( ´◔ ω◔`) ノシ",
            ["gun"] = @"︻╦╤─",
            ["hadouken"] = @"༼つಠ益ಠ༽つ ─=≡ΣO))",
            ["hammerandsickle"] = @"☭",
            ["handleft"] = @"☜",
            ["handright"] = @"☞",
            ["haha"] = @"٩(^‿^)۶",
            ["happy"] = @"٩( ๑╹ ꇴ╹)۶",
            ["happygarry"] = @"ᕕ( ᐛ )ᕗ",
            ["h"] = @"♥",
            ["hello"] = @"(ʘ‿ʘ)╯",
            ["highfive"] = @"._.)/\(._.",
            ["hitting"] = @"( ｀皿´)｡ﾐ/",
            ["hug"] = @"(づ｡◕‿‿◕｡)づ",
            ["iknowright"] = @"┐｜･ิω･ิ#｜┌",
            ["illuminati"] = @"୧(▲ᴗ▲)ノ",
            ["infinity"] = @"∞",
            ["inlove"] = @"(っ´ω`c)♡",
            ["int"] = @"∫",
            ["internet"] = @"ଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛ",
            ["interrobang"] = @"‽",
            ["jake"] = @"(❍ᴥ❍ʋ)",
            ["kawaii"] = @"≧◡≦",
            ["keen"] = @"┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ",
            ["kiahh"] = @"~\(≧▽≦)/~",
            ["kiss"] = @"(づ ￣ ³￣)づ",
            ["kyubey"] = @"／人◕ ‿‿ ◕人＼",
            ["lambda"] = @"λ",
            ["lazy"] = @"_(:3」∠)_",
            ["left"] = @"←",
            ["lenny"] = @"( ͡° ͜ʖ ͡°)",
            ["lennybill"] = @"[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]",
            ["lennyfight"] = @"(ง ͠° ͟ʖ ͡°)ง",
            ["lennyflip"] = @"(ノ ͡° ͜ʖ ͡°ノ)   ︵ ( ͜。 ͡ʖ ͜。)",
            ["lennygang"] = @"( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)",
            ["lennyshrug"] = @"¯\_( ͡° ͜ʖ ͡°)_/¯",
            ["lennysir"] = @"( ಠ ͜ʖ ರೃ)",
            ["lennystalker"] = @"┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴",
            ["lennystrong"] = @"ᕦ( ͡° ͜ʖ ͡°)ᕤ",
            ["lennywizard"] = @"╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ",
            ["lol"] = @"L(° O °L)",
            ["look"] = @"(ಡ_ಡ)☞",
            ["love"] = @"♥‿♥",
            ["lovebear"] = @"ʕ♥ᴥ♥ʔ",
            ["lumpy"] = @"꒰ ꒡⌓꒡꒱",
            ["luv"] = @"-`ღ´-",
            ["magic"] = @"ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ,",
            ["magicflip"] = @"(/¯◡ ‿ ◡)/¯ ~ ┻━┻",
            ["meep"] = @"\(°^°)/",
            ["meh"] = @"ಠ_ಠ",
            ["mistyeyes"] = @"ಡ_ಡ",
            ["monster"] = @"༼ ༎ຶ ෴ ༎ຶ༽",
            ["natural"] = @"♮",
            ["needle"] = @"┌(◉ ͜ʖ◉)つ┣▇▇▇═──",
            ["nice"] = @"( ͡° ͜ °)",
            ["no"] = @"→_←",
            ["noclue"] = @"／人◕ __ ◕人＼",
            ["nom"] = @"(っˆڡˆς)",
            ["note"] = @"♫",
            ["nuclear"] = @"☢",
            ["nyan"] = @"~=[,,_,,]:3",
            ["nyeh"] = @"@^@",
            ["ohshit"] = @"( º﹃º )",
            ["omg"] = @"◕_◕",
            ["1/8"] = @"⅛",
            ["1/4"] = @"¼",
            ["1/2"] = @"½",
            ["1/3"] = @"⅓",
            ["opt"] = @"⌥",
            ["orly"] = @"(눈_눈)",
            ["ohyou"] = @"(◞థ౪థ)ᴖ",
            ["peace"] = @"✌(-‿-)✌",
            ["pear"] = @"(__>-",
            ["pi"] = @"π",
            ["pingpong"] = @"( •_•)O*¯`·.¸.·´¯`°Q(•_• )",
            ["plain"] = @"._.",
            ["pleased"] = @"(˶‾᷄ ⁻̫ ‾᷅˵)",
            ["point"] = @"(☞ﾟヮﾟ)☞",
            ["pooh"] = @"ʕ •́؈•̀)",
            ["porcupine"] = @"(•ᴥ• )́`́'́`́'́⻍",
            ["pound"] = @"£",
            ["praise"] = @"(☝ ՞ਊ ՞)☝",
            ["punch"] = @"O=('-'Q)",
            ["rage"] = @"t(ಠ益ಠt)",
            ["rageflip"] = @"(ノಠ益ಠ)ノ彡┻━┻",
            ["rainbowcat"] = @"(=^･ｪ･^=))ﾉ彡☆",
            ["really"] = @"ò_ô",
            ["r"] = @"®",
            ["right"] = @"→",
            ["riot"] = @"୧༼ಠ益ಠ༽୨",
            ["rolleyes"] = @"(◔_◔)",
            ["rose"] = @"✿ڿڰۣ—",
            ["run"] = @"(╯°□°)╯",
            ["sad"] = @"ε(´סּ︵סּ`)з",
            ["saddonger"] = @"ヽ༼ຈʖ̯ຈ༽ﾉ",
            ["sadlenny"] = @"( ͡° ʖ̯ ͡°)",
            ["7/8"] = @"⅞",
            ["sharp"] = @"♯",
            ["shout"] = @"╚(•⌂•)╝",
            ["shrug"] = @"¯\_(ツ)_/¯",
            ["shy"] = @"=^_^=",
            ["sigma"] = @"Σ",
            ["skull"] = @"☠",
            ["smile"] = @"ツ",
            ["smiley"] = @"☺︎",
            ["smirk"] = @"¬‿¬",
            ["snowman"] = @"☃",
            ["sob"] = @"(;´༎ຶД༎ຶ`)",
            ["spade"] = @"♠",
            ["sqrt"] = @"√",
            ["squid"] = @"<コ:彡",
            ["star"] = @"★",
            ["strong"] = @"ᕙ(⇀‸↼‶)ᕗ",
            ["suicide"] = @"ε/̵͇̿̿/’̿’̿ ̿(◡︵◡)",
            ["sum"] = @"∑",
            ["sun"] = @"☀",
            ["surprised"] = @"(๑•́ ヮ •̀๑)",
            ["surrender"] = @"\_(-_-)_/",
            ["stalker"] = @"┬┴┬┴┤(･_├┬┴┬┴",
            ["swag"] = @"(̿▀̿‿ ̿▀̿ ̿)",
            ["sword"] = @"o()xxxx[{::::::::::::::::::>",
            ["tabledown"] = @"┬─┬ ノ( ゜-゜ノ)",
            ["tableflip"] = @"(ノ ゜Д゜)ノ ︵ ┻━┻",
            ["tau"] = @"τ",
            ["tears"] = @"(ಥ﹏ಥ)",
            ["terrorist"] = @"୧༼ಠ益ಠ༽︻╦╤─",
            ["thanks"] = @"\(^-^)/",
            ["therefore"] = @"⸫",
            ["3/8"] = @"⅜",
            ["tiefighter"] = @"|=-(¤)-=|",
            ["tired"] = @"(=____=)",
            ["toldyouso"] = @"☜(꒡⌓꒡)",
            ["toogood"] = @"ᕦ(òᴥó)ᕥ",
            ["tm"] = @"™",
            ["triangle"] = @"▲",
            ["2/3"] = @"⅔",
            ["unflip"] = @"┬──┬ ノ(ò_óノ)",
            ["up"] = @"↑",
            ["victory"] = @"(๑•̀ㅂ•́)ง✧",
            ["wat"] = @"(ÒДÓױ)",
            ["wave"] = @"( * ^ *) ノシ",
            ["whaa"] = @"Ö",
            ["whistle"] = @"(っ^з^)♪♬",
            ["whoa"] = @"(°o•)",
            ["why"] = @"ლ(`◉◞౪◟◉‵ლ)",
            ["woo"] = @"＼(＾O＾)／",
            ["wtf"] = @"(⊙＿⊙')",
            ["wut"] = @"⊙ω⊙",
            ["yay"] = @"\( ﾟヮﾟ)/",
            ["yeah"] = @"(•̀ᴗ•́)و ̑̑",
            ["yen"] = @"¥",
            ["yinyang"] = @"☯",
            ["yolo"] = @"Yᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ",
            ["youkids"] = @"ლ༼>╭ ͟ʖ╮<༽ლ",
            ["y u no"] = @"(屮ﾟДﾟ)屮 Y U NO",
            ["zen"] = @"⊹╰(⌣ʟ⌣)╯⊹",
            ["zoidberg"] = @"(V) (°,,,,°) (V)",
            ["zombie"] = @"[¬º-°]¬"
        };

        public object GetResult(Query query)
        {
            if (query.IsHelp)
            {
                return HelpTable(
                    ("shrug", emoticons["shrug"]),
                    ("1/8", emoticons["1/8"])
                );
            }

            var input = query.OriginalInput.Trim();
            if (triggers.Contains(input))
            {
                return RenderAll();
            }

            if (emoticons.ContainsKey(input))
            {
                return Text(emoticons[input]);
            }

            return null;
        }
        
        private object RenderAll()
        {
            var list = new List<object>();

            list.Add(SectionHeader("Emoticons:"));

            var rows = from kvp in emoticons
                       let description = kvp.Key
                       select (description, kvp.Value);

            list.Add(NameValueTable(rows.ToArray()));

            return list;
        }
    }
}